[2024-07-08T09:13:17.912+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: DAG_9.print_hello scheduled__2024-07-08T09:11:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
